const CONFIG={guideUrl:"https://juliemarlina-collab.github.io/Smart-MUET-Guide/",googleFormEmbedUrl:"",googleFormPublicUrl:""};
const STORE_KEY="smgTestingPortal";const defaultState={consent:false,baseline:false,guide:false,tasks:{speaking:false,reading:false,listening:false,writing:false},feedback:false};
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORE_KEY)||"{}")} }catch(e){return {...defaultState}}}
function saveState(s){localStorage.setItem(STORE_KEY,JSON.stringify(s))}
function setDone(key,value=true){const s=loadState();if(key.startsWith("tasks.")){const k=key.split(".")[1];s.tasks={...s.tasks,[k]:value}}else s[key]=value;saveState(s);renderProgress()}
function completedSteps(s){let n=0;if(s.consent)n++;if(s.baseline)n++;if(s.guide)n++;if(Object.values(s.tasks||{}).every(Boolean))n++;if(s.feedback)n++;return n}
function renderProgress(){const s=loadState(),done=completedSteps(s);document.querySelectorAll("[data-progress]").forEach(el=>el.textContent=`${done}/5`);document.querySelectorAll("[data-progress-bar]").forEach(el=>el.style.width=`${(done/5)*100}%`);document.querySelectorAll("[data-task]").forEach(el=>el.checked=!!s.tasks?.[el.dataset.task])}
function launchGuide(){setDone("guide",true);window.open(CONFIG.guideUrl,"_blank","noopener")}
function setupGoogleForm(){const f=document.querySelector("#googleFormFrame"),p=document.querySelector("#formPlaceholder"),o=document.querySelector("#openForm");if(f&&CONFIG.googleFormEmbedUrl){f.src=CONFIG.googleFormEmbedUrl;f.hidden=false;if(p)p.hidden=true}if(o&&CONFIG.googleFormPublicUrl){o.href=CONFIG.googleFormPublicUrl;o.hidden=false}}
document.addEventListener("DOMContentLoaded",()=>{renderProgress();setupGoogleForm();document.querySelectorAll("[data-launch-guide]").forEach(b=>b.addEventListener("click",launchGuide));document.querySelectorAll("[data-task]").forEach(box=>box.addEventListener("change",()=>setDone(`tasks.${box.dataset.task}`,box.checked)));const c=document.querySelector("#consentForm");if(c)c.addEventListener("submit",e=>{e.preventDefault();if(!document.querySelector("#consentAgree")?.checked){alert("Please select 'I agree' to continue.");return}setDone("consent",true);location.href="journey.html#baseline"});const b=document.querySelector("#baselineForm");if(b)b.addEventListener("submit",e=>{e.preventDefault();setDone("baseline",true);location.href="tasks.html"})});
